# Gemfile for Coffeetron
source 'http://rubygems.org'

gem 'rake', '~> 0.8.7'
gem 'rails', '3.0.7'
gem 'cancan', '1.6.5'
gem 'devise', '1.3.4'
gem 'decent_exposure', '1.0.1'
gem 'dynamic_form', '1.1.4'
gem 'i18n'
gem 'pg', '0.11.0'
gem 'haml', '3.1.1'
gem 'haml-rails', '0.3.4'
gem 'hpricot', '0.8.4'
gem 'jspec', '4.3.3'
gem 'unicorn', '3.6.2'
gem 'capistrano', '2.6.0'
gem 'ruby_parser' 
gem 'sass'
gem 'sexp_processor'
gem 'test_notifier'
gem 'ZenTest', '4.5.0'
gem 'carrierwave', '>= 0.5.3'
gem 'mini_magick'
gem 'nested_form'
gem 'rdiscount'
#gem 'bluecloth'

group :development, :test do
  gem 'rspec', '2.6.0'
  gem 'rspec-rails', '2.6.1'
  gem 'watchr', '0.7'
  gem 'factory_girl', '1.3.3'
  gem 'factory_girl_rails', '1.0.1'
  gem 'autotest', '4.4.6'
  gem 'autotest-rails'
  gem 'launchy'
  gem 'faker', '0.9.5'
  gem 'capybara', '1.0.0.beta1'
  gem 'cucumber', '0.10.3'
  gem 'cucumber-rails', '0.5.1'
  gem 'database_cleaner'
  gem 'spork', '0.9.0.rc5'
end
