# Gemfile for Coffeetron
source 'http://rubygems.org'

gem 'rake'
gem 'rails', '3.0.3'
gem 'cancan'
gem 'dynamic_form'
gem 'i18n'
gem 'pg'
gem 'haml'
gem 'haml-rails'
gem 'hpricot'
gem 'jspec'
gem 'unicorn'
gem 'capistrano'
gem 'ruby_parser'
gem 'sexp_processor'
gem 'test_notifier'
gem 'ZenTest'

group :development, :test do
  gem 'rspec'
  gem 'rspec-rails'
  gem 'factory_girl'
  gem 'factory_girl_rails'
  gem 'autotest'
  gem 'autotest-rails'
  gem 'launchy'
  gem 'faker'
  gem 'capybara'
end
