<%
rerun = File.file?('rerun.txt') ? IO.read('rerun.txt') : ""
rerun_opts = rerun.to_s.strip.empty? ? "--format #{ENV['CUCUMBER_FORMAT'] || 'progress'} features" : "--format #{ENV['CUCUMBER_FORMAT'] || 'pretty'} #{rerun}"
#default_opts = "--format #{ENV['CUCUMBER_FORMAT'] || 'progress'} --strict --tags ~@wip,~@todo"
default_opts = "--strict --tags ~@wip --tags ~@todo"
shared_opts = "--format pretty --require features"
%>

default: --drb <%= shared_opts %> <%= default_opts %>
wip: --drb <%= shared_opts %> --tags @wip --wip features
todo: --drb <%= shared_opts %> --tags @todo features
rerun: --drb <%= rerun_opts %> --format rerun --out rerun.txt --strict --tags ~@wip features
